"""add card_expenses

Revision ID: 19ff4b3d5779
Revises: 686d5c77d7d0
Create Date: 2026-04-18 14:34:27.375199

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '19ff4b3d5779'
down_revision: str | Sequence[str] | None = '686d5c77d7d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=True),
    sa.Column('organ_code', sa.String(length=20), nullable=False),
    sa.Column('organ_name', sa.String(length=255), nullable=False),
    sa.Column('management_unit_code', sa.String(length=20), nullable=True),
    sa.Column('management_unit_name', sa.String(length=255), nullable=True),
    sa.Column('holder_name', sa.String(length=255), nullable=True),
    sa.Column('holder_cpf', sa.String(length=20), nullable=True),
    sa.Column('holder_role', sa.String(length=255), nullable=True),
    sa.Column('card_number', sa.String(length=30), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('transaction_year', sa.Integer(), nullable=True),
    sa.Column('transaction_month', sa.Integer(), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_cnpj', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_expenses_external_id'), 'card_expenses', ['external_id'], unique=True)
    op.create_index(op.f('ix_card_expenses_holder_name'), 'card_expenses', ['holder_name'], unique=False)
    op.create_index(op.f('ix_card_expenses_organ_code'), 'card_expenses', ['organ_code'], unique=False)
    op.create_index('ix_card_expenses_organ_year', 'card_expenses', ['organ_code', 'transaction_year'], unique=False)
    op.create_index(op.f('ix_card_expenses_politician_id'), 'card_expenses', ['politician_id'], unique=False)
    op.create_index(op.f('ix_card_expenses_supplier_cnpj'), 'card_expenses', ['supplier_cnpj'], unique=False)
    op.create_index(op.f('ix_card_expenses_supplier_name'), 'card_expenses', ['supplier_name'], unique=False)
    op.create_index('ix_card_expenses_supplier_organ', 'card_expenses', ['supplier_cnpj', 'organ_code'], unique=False)
    op.create_index(op.f('ix_card_expenses_transaction_date'), 'card_expenses', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_card_expenses_transaction_year'), 'card_expenses', ['transaction_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_expenses_transaction_year'), table_name='card_expenses')
    op.drop_index(op.f('ix_card_expenses_transaction_date'), table_name='card_expenses')
    op.drop_index('ix_card_expenses_supplier_organ', table_name='card_expenses')
    op.drop_index(op.f('ix_card_expenses_supplier_name'), table_name='card_expenses')
    op.drop_index(op.f('ix_card_expenses_supplier_cnpj'), table_name='card_expenses')
    op.drop_index(op.f('ix_card_expenses_politician_id'), table_name='card_expenses')
    op.drop_index('ix_card_expenses_organ_year', table_name='card_expenses')
    op.drop_index(op.f('ix_card_expenses_organ_code'), table_name='card_expenses')
    op.drop_index(op.f('ix_card_expenses_holder_name'), table_name='card_expenses')
    op.drop_index(op.f('ix_card_expenses_external_id'), table_name='card_expenses')
    op.drop_table('card_expenses')
    # ### end Alembic commands ###
