"""initial_schema

Revision ID: 32197fed136b
Revises: 
Create Date: 2026-04-14 18:54:18.939047

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '32197fed136b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_abbreviation'), 'parties', ['abbreviation'], unique=True)
    op.create_table('politicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('legislature', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_politicians_external_id'), 'politicians', ['external_id'], unique=True)
    op.create_index(op.f('ix_politicians_legislature'), 'politicians', ['legislature'], unique=False)
    op.create_index(op.f('ix_politicians_name'), 'politicians', ['name'], unique=False)
    op.create_index(op.f('ix_politicians_party_id'), 'politicians', ['party_id'], unique=False)
    op.create_index(op.f('ix_politicians_uf'), 'politicians', ['uf'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_document', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('doc_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_external_id'), 'expenses', ['external_id'], unique=True)
    op.create_index(op.f('ix_expenses_politician_id'), 'expenses', ['politician_id'], unique=False)
    op.create_index(op.f('ix_expenses_year'), 'expenses', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_year'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_politician_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_external_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_politicians_uf'), table_name='politicians')
    op.drop_index(op.f('ix_politicians_party_id'), table_name='politicians')
    op.drop_index(op.f('ix_politicians_name'), table_name='politicians')
    op.drop_index(op.f('ix_politicians_legislature'), table_name='politicians')
    op.drop_index(op.f('ix_politicians_external_id'), table_name='politicians')
    op.drop_table('politicians')
    op.drop_index(op.f('ix_parties_abbreviation'), table_name='parties')
    op.drop_table('parties')
    # ### end Alembic commands ###
