"""add_mandate_end_to_politicians

Revision ID: 686d5c77d7d0
Revises: fac9b956ab2d
Create Date: 2026-04-15 23:52:45.458050

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '686d5c77d7d0'
down_revision: str | Sequence[str] | None = 'fac9b956ab2d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('politicians', sa.Column('mandate_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('politicians', 'mandate_end')
    # ### end Alembic commands ###
