"""add amendments

Revision ID: a9a9febe9fca
Revises: 19ff4b3d5779
Create Date: 2026-04-18 21:53:31.516563

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9a9febe9fca"
down_revision: str | Sequence[str] | None = "19ff4b3d5779"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amendments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_code", sa.String(length=50), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("amendment_type", sa.String(length=100), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("author_name", sa.String(length=255), nullable=True),
        sa.Column("politician_id", sa.Integer(), nullable=True),
        sa.Column("amendment_number", sa.String(length=20), nullable=True),
        sa.Column("locality", sa.String(length=255), nullable=True),
        sa.Column("function_name", sa.String(length=100), nullable=True),
        sa.Column("subfunction_name", sa.String(length=100), nullable=True),
        sa.Column("committed_value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("liquidated_value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("paid_value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("remainder_inscribed", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("remainder_canceled", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("remainder_paid", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("is_pix", sa.Boolean(), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["politician_id"],
            ["politicians.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_amendments_amendment_type"), "amendments", ["amendment_type"], unique=False
    )
    op.create_index(op.f("ix_amendments_author_name"), "amendments", ["author_name"], unique=False)
    op.create_index(
        "ix_amendments_author_year", "amendments", ["author_name", "year"], unique=False
    )
    op.create_index(
        op.f("ix_amendments_external_code"), "amendments", ["external_code"], unique=True
    )
    op.create_index(
        op.f("ix_amendments_function_name"), "amendments", ["function_name"], unique=False
    )
    op.create_index(op.f("ix_amendments_locality"), "amendments", ["locality"], unique=False)
    op.create_index(
        op.f("ix_amendments_politician_id"), "amendments", ["politician_id"], unique=False
    )
    op.create_index(
        "ix_amendments_politician_year", "amendments", ["politician_id", "year"], unique=False
    )
    op.create_index(op.f("ix_amendments_year"), "amendments", ["year"], unique=False)
    op.create_index(
        "ix_amendments_year_type", "amendments", ["year", "amendment_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_amendments_year_type", table_name="amendments")
    op.drop_index(op.f("ix_amendments_year"), table_name="amendments")
    op.drop_index("ix_amendments_politician_year", table_name="amendments")
    op.drop_index(op.f("ix_amendments_politician_id"), table_name="amendments")
    op.drop_index(op.f("ix_amendments_locality"), table_name="amendments")
    op.drop_index(op.f("ix_amendments_function_name"), table_name="amendments")
    op.drop_index(op.f("ix_amendments_external_code"), table_name="amendments")
    op.drop_index("ix_amendments_author_year", table_name="amendments")
    op.drop_index(op.f("ix_amendments_author_name"), table_name="amendments")
    op.drop_index(op.f("ix_amendments_amendment_type"), table_name="amendments")
    op.drop_table("amendments")
    # ### end Alembic commands ###
