"""add_description_to_votes

Revision ID: ad9e38d101f9
Revises: 9eeb7ce74443
Create Date: 2026-04-15 01:34:42.271839

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad9e38d101f9"
down_revision: str | Sequence[str] | None = "9eeb7ce74443"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_politicians_external_id"), "politicians", ["external_id"], unique=False
    )
    op.add_column("votes", sa.Column("description", sa.String(length=500), nullable=True))
    op.drop_constraint(op.f("uq_votes_votacao_politician"), "votes", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_votes_votacao_politician"),
        "votes",
        ["external_votacao_id", "politician_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("votes", "description")
    op.drop_index(op.f("ix_politicians_external_id"), table_name="politicians")
    # ### end Alembic commands ###
