"""add_propositions_and_votes

Revision ID: add890c6769f
Revises: 32197fed136b
Create Date: 2026-04-14 19:45:38.578368

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'add890c6769f'
down_revision: str | Sequence[str] | None = '32197fed136b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('prop_type', sa.String(length=20), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propositions_author_id'), 'propositions', ['author_id'], unique=False)
    op.create_index(op.f('ix_propositions_external_id'), 'propositions', ['external_id'], unique=True)
    op.create_index(op.f('ix_propositions_prop_type'), 'propositions', ['prop_type'], unique=False)
    op.create_index(op.f('ix_propositions_year'), 'propositions', ['year'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_votacao_id', sa.String(length=50), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('proposition_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.ForeignKeyConstraint(['proposition_id'], ['propositions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_external_votacao_id'), 'votes', ['external_votacao_id'], unique=False)
    op.create_index(op.f('ix_votes_politician_id'), 'votes', ['politician_id'], unique=False)
    op.create_index(op.f('ix_votes_proposition_id'), 'votes', ['proposition_id'], unique=False)
    op.create_index(op.f('ix_votes_session_date'), 'votes', ['session_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_session_date'), table_name='votes')
    op.drop_index(op.f('ix_votes_proposition_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_politician_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_external_votacao_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_propositions_year'), table_name='propositions')
    op.drop_index(op.f('ix_propositions_prop_type'), table_name='propositions')
    op.drop_index(op.f('ix_propositions_external_id'), table_name='propositions')
    op.drop_index(op.f('ix_propositions_author_id'), table_name='propositions')
    op.drop_table('propositions')
    # ### end Alembic commands ###
