"""restore_votes_unique_constraint

Revision ID: c1fed9a41cb9
Revises: ad9e38d101f9
Create Date: 2026-04-15 01:50:21.067052

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1fed9a41cb9"
down_revision: str | Sequence[str] | None = "ad9e38d101f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_votes_votacao_politician", "votes", ["external_votacao_id", "politician_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_votes_votacao_politician", "votes", type_="unique")
    # ### end Alembic commands ###
