"""add_proposition_ref_to_votes

Revision ID: fac9b956ab2d
Revises: c1fed9a41cb9
Create Date: 2026-04-15 13:28:32.689532

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fac9b956ab2d"
down_revision: str | Sequence[str] | None = "c1fed9a41cb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("votes", sa.Column("proposition_ref", sa.String(length=50), nullable=True))
    op.create_index(op.f("ix_votes_proposition_ref"), "votes", ["proposition_ref"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_votes_proposition_ref"), table_name="votes")
    op.drop_column("votes", "proposition_ref")
    # ### end Alembic commands ###
